### PR TITLE
Hw3

### PR DESCRIPTION
**Pull request by jon-bell**

### CODE REVIEW

**Comment by mwand** [comment]
I'm only halfway through Part 1, and I haven't read the details of this PR.  But here are my notes on the assignment so far:

Lots of linting errors in the handout as distributed.  Is this intentional?

filename: CoveyRoomREST.test.ts vs CoveyRoomRest.test.ts ?  I think it is spelled differently in different places.

package.json: @types/express is listed in dependencies, not dev-dependencies

CoveyRoomRequestHandlers exports both interfaces and functions: this seems to be a design flaw?  Was that one of the things that you intended for students to comment on in one of the "other comments" sections?

Also, should CoveyTypes.ts be in types/ ?  And in general, there seems to be no good rationale for what's in types/ .  But probably this kind of stuff was already in previous hws, and shouldn't be changed now.  (Especially if there's going to be a refactoring assignment :)

**Comment by mwand** [comment]
Also, my implementation of the test 'CoveyRoomCreateAPI is flaky-- sometimes it times out.  Again, dunno if you intended this to happen. 
````
describe('CoveyRoomCreateAPI', () => {
    it.each(ConfigureTest('CR'))('Allows for multiple rooms with the same friendlyName [%s]', 
    async (testConfiguration: string) => {
      StartTest(testConfiguration);
      const roomCreateRequest = {friendlyName: "room1", isPubliclyListed: true}
      const p1 = apiClient.createRoom(roomCreateRequest);
      const p2 = apiClient.createRoom(roomCreateRequest);
      await expect(Promise.all([p1,p2])).resolves.toBeDefined()
      
    }
    )
  })
````
Yeah, probably should have checked to see that the returned roomIDs are different :)

**Comment by jon-bell** [comment]
> Lots of linting errors in the handout as distributed. Is this intentional?

John B pointed this out - the handout has been updated and these are now gone.

> filename: CoveyRoomREST.test.ts vs CoveyRoomRest.test.ts ? I think it is spelled differently in different places.

Updated HW3.md to be consistent

> package.json: @types/express is listed in dependencies, not dev-dependencies

What is the rationale for only listing this in dev-dependencies? Express is used in the app in production, too.

> CoveyRoomRequestHandlers exports both interfaces and functions: this seems to be a design flaw? Was that one of the things that you intended for students to comment on in one of the "other comments" sections?

Indeed, a bad design choice. I had originally changed this for HW3, but making that change would require that we distribute our solution to CoveyRoomRequestHandlers and CoveyRoomController and friends along with the handout for HW3. But, this would push back the release of HW3 until after the late deadline of HW2. So, we live with it.

> Also, should CoveyTypes.ts be in types/ ? And in general, there seems to be no good rationale for what's in types/ . 

But probably this kind of stuff was already in previous hws, and shouldn't be changed now. (Especially if there's going to be a refactoring assignment :)
Same answer as the one above.

**Comment by jon-bell** [comment]
Also, FYI, I can not reproduce that flaky test 🤷

**Pull request merged**
