### PR TITLE
First draft of project assignment overview

### PR DESCRIPTION
**Pull request by jon-bell**
Here's the first draft of the document that I'd like to release by this Friday, describing a high level overview of the project deliverables. The rubrics and more detailed specifications for each deliverable will be released following the timeline on the class schedule, so there will still be time to fine-tune each deliverable and its grading criteria.

### CODE REVIEW

**Review by boyland — COMMENTED** [review]
It looks very good.

March 12 - April 12 is not really five weeks.  Is one of the dates wrong?  We probably could extend the final deadline later.

**Comment by jon-bell** [comment]
Oops, the last day should be April 15

**Comment by mwand** [comment]
implemente. => implemented.   (Sorry, not sure how to do that edit directly).

re Work Breakdown:  Last time, we decided not to ask for a weekly breakdown because we hadn't taught them anything about estimation.  I suppose it's good to have them propose it up front, so they will learn how hard it is to produce a realistic schedule.

Should we ask them to propose a development process here (eg: branches vs. forks, code review process, etc)?

re Documentation:  I think the phrase "A README" belongs with the first bullet ("instructions...").  The other documentation deliverables seem quite a bit larger than would neatly fit into a single README .md.

I the section on final deliverables will need refinement as to length, etc, etc.  Last time we asked them to reflect on their own development process and how it worked out for them.   We also asked them to reflect on how their vision of the project evolved (eg, "we proposed doing XX, but we backed off to just doing X because...").  I think asking for some reflection in the final deliverable is a valuable learning experience.

**Comment by jon-bell** [comment]
>implemente. => implemented. (Sorry, not sure how to do that edit directly).

No problem - fixed.

>re Work Breakdown: Last time, we decided not to ask for a weekly breakdown because we hadn't taught them anything about estimation. I suppose it's good to have them propose it up front, so they will learn how hard it is to produce a realistic schedule.

I think that my objections last term to doing this was: "We haven't taught it to them, so how can we grade it?" but my rationale for including it this term is: "We'll just do spec grading, and the spec is: you need to make some schedule, with a reasonable set of tasks" - it doesn't really matter how off they are on the schedule, but they need to make one which we can refer back to in team meeting to ask how things are going.

>re Documentation: I think the phrase "A README" belongs with the first bullet ("instructions..."). The other documentation deliverables seem quite a bit larger than would neatly fit into a single README .md.

Thanks - tweaked.

>Last time we asked them to reflect on their own development process and how it worked out for them. We also asked them to reflect on how their vision of the project evolved (eg, "we proposed doing XX, but we backed off to just doing X because..."). I think asking for some reflection in the final deliverable is a valuable learning experience.

I agree that this is valuable. However, I had two reasons to not include that here:
1. I think my implicit expectation is that the entire "final deliverable" (implementation + docs) could be made public by the students without resulting in any academic dishonesty issues. I think that the reflection should not be made public
2. I think that some of the reflection pieces should go into the final exam, so that we can evaluate each student on those pieces (rather than as a team assignment)

Separately, I think that some kind of a post-mortem would be valuable, but I'm not sure how to best accomplish that while also allowing for the project to be submitted at the very end of the term.

**Comment by boyland** [comment]
I support Jon's handling of Mitch's comments.

**Comment by mwand** [comment]
Jon wrote:

Last time we asked them to reflect on their own development process and how
it worked out for them. We also asked them to reflect on how their vision
of the project evolved (eg, "we proposed doing XX, but we backed off to
just doing X because..."). I think asking for some reflection in the final
deliverable is a valuable learning experience.
I agree that this is valuable. However, I had two reasons to not include
that here:


   1. I think my implicit expectation is that the entire "final
   deliverable" (implementation + docs) could be made public by the students
   without resulting in any academic dishonesty issues. I think that the
   reflection should not be made public
   2. I think that some of the reflection pieces should go into the final
   exam, so that we can evaluate each student on those pieces (rather than as
   a team assignment)

I don't see how making the reflection piece public would result in academic
dishonesty issues.  It might, however, be inappropriate in a portfolio.  We
could make a reflection mandatory as a separate deliverable, submitted
through a separate channel (say, Gradescope).  That would have the
advantage of making the reflection an individual assignment rather than a
team one, which I think is good.

I don't see how the reflection piece would fit into a final exam.  Among
other things, the exam is time-limited, whereas reflections should not be
time-limited.

**Comment by jon-bell** [comment]
@mwand OK - you have me convinced. I added 3 bullets for an individual reflection, which are hopefully sufficiently vague that we can discuss and fine-tune them over the next few weeks. Let me know if you have any other thoughts, or if this is ready to ship.

**Comment by jon-bell** [comment]
(Also other small change: I put down the final demo as a video submission - enough teams seemed to opt-in to doing a pre-recorded video last term to indicate it's not a major burden to produce, and it makes logistics for scheduling demos much easier)

**Comment by mwand** [comment]
Litmus

**Comment by mwand** [comment]
Autocorrected from lgtm

**Pull request merged**
